#### NVSS Overdose Data Analysis

In [2]:
# Import Libraries
import numpy as np
import pandas as pd

In [3]:
mort_2018 = pd.read_csv('/home/h6x/git_projects/ornl-nvss-overdose-data/data/raw_data/mort_2018.csv')

/tmp/ipykernel_3329655/3684067581.py:1: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  mort_2018 = pd.read_csv('/home/h6x/git_projects/ornl-nvss-overdose-data/data/raw_data/mort_2018.csv')


In [4]:
mort_2018.head(20)

record_type  resident_status occurrence_state  occurrence_county  \
0             2                3               AK                 20   
1             1                1               AK                 20   
2             1                1               AK                170   
3             1                1               AK                 20   
4             2                2               AK                 20   
5             2                2               AK                240   
6             1                1               AK                 90   
7             1                1               AK                261   
8             1                1               AK                122   
9             1                1               AK                 90   
10            1                1               AK                 90   
11            1                1               AK                122   
12            1                1               AK                 90   
13            1                1               AK                 20   
14            1                1               AK                 20   
15            2                3               AK                122   
16            1                1               AK                 20   
17            1                1               AK                 20   
18            1                1               AK                 20   
19            1                1               AK                 90   

   occurrence_expanded_state  population_size residence_state  \
0                         AK                2              WY   
1                         AK                2              AK   
2                         AK                4              AK   
3                         AK                2              AK   
4                         AK                2              AK   
5                         AK                9              AK   
6                         AK                4              AK   
7                         AK                9              AK   
8                         AK                4              AK   
9                         AK                4              AK   
10                        AK                4              AK   
11                        AK                4              AK   
12                        AK                4              AK   
13                        AK                2              AK   
14                        AK                2              AK   
15                        AK                4              CA   
16                        AK                2              AK   
17                        AK                2              AK   
18                        AK                2              AK   
19                        AK                4              AK   

   state_country_recode  residence_county  residence_city  ...  \
0                    WY                33           99999  ...   
1                    AK                20            3000  ...   
2                    AK               170           99999  ...   
3                    AK                20            3000  ...   
4                    AK               220           99999  ...   
5                    AK                90           99999  ...   
6                    AK                90           99999  ...   
7                    AK               261           99999  ...   
8                    AK               122           99999  ...   
9                    AK                90           99999  ...   
10                   AK                90           99999  ...   
11                   AK               122           99999  ...   
12                   AK                90           99999  ...   
13                   AK                20            3000  ...   
14                   AK                20            3000  ...   
15                   CA               111           54652  ...   
16 

In [5]:
mort_2018.shape

(2846305, 59)

In [6]:
mort_2018['occurrence_state'].unique()

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [7]:
len(mort_2018['occurrence_state'].unique())

51

In [8]:
tn_mort_2018 = mort_2018[mort_2018['occurrence_state'] == 'TN']

In [9]:
tn_mort_2018.shape

(74850, 59)

In [12]:
tn_mort_2018['occurrence_county'].unique()

array([119,  37,  93,  79, 149,  31, 187, 165,  59,   3,  11,  65, 117,
       183,  99,   9,  43,  13,  51, 147,  73,  41,  63, 163, 189, 159,
       115, 135, 113,  17, 105,  19,   1,  53, 179,  89,  25, 153,  29,
       185, 177, 167,  21, 173, 125,  39, 145, 157,   7, 155,  55,  35,
        61,  85, 103,   5, 131, 181,  87,  71,  57, 143,  27, 111,  77,
       107, 129,  23, 141, 151, 101, 123, 161, 133,  83, 109,  97,  15,
        45,  75, 139,  81, 127,  47,  91, 171,  69, 137,  49,  33, 169,
       121,  67,  95, 175])

In [13]:
len(tn_mort_2018['occurrence_county'].unique())

95

In [14]:
# get column names to a list

col_names = tn_mort_2018.columns.tolist()

In [15]:
col_names

['record_type',
 'resident_status',
 'occurrence_state',
 'occurrence_county',
 'occurrence_expanded_state',
 'population_size',
 'residence_state',
 'state_country_recode',
 'residence_county',
 'residence_city',
 'residence_city_population_size',
 'residence_met_nonmet_county',
 'residence_expanded_state',
 'state_of_birth',
 'state_of_birth_recode',
 'education_1989_revision',
 'education_2003_revision',
 'education_reporting_flag',
 'month_of_death',
 'sex',
 'detail_age',
 'age_substitution_flag',
 'age_recode_52',
 'age_recode_27',
 'age_recode_12',
 'infant_age_recode_22',
 'place_of_death',
 'marital_status',
 'day_of_week',
 'current_data_year',
 'injury_at_work',
 'manner_of_death',
 'method_of_disposition',
 'autopsy',
 'certifier',
 'tobacco_use_contributed',
 'pregnancy_status',
 'activity_code',
 'place_of_injury',
 'cause of death_icd10',
 'cause_recode_358',
 'cause_recode_113',
 'infant_cause_recode_130',
 'cause_recode_39',
 'number_entity_axis_conditions',
 'entity_a

In [18]:
tn_mort_2018['month_of_death'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
# get the record count for each "occurrence_county"

tn_mort_2018['occurrence_county'].value_counts()

occurrence_county
157    10327
37      9381
93      6709
65      5410
163     3130
       ...  
127       64
67        64
95        62
175       53
137       50
Name: count, Length: 95, dtype: int64

In [22]:
tn_mort_2018['sex'].unique()

array(['F', 'M'], dtype=object)

In [23]:
tn_mort_2018['detail_age'].unique()

array([1094, 1097, 1063, 1076, 1090, 1054, 1080, 1068, 1060, 1079, 1045,
       1038, 1083, 1078, 1028, 1059, 1067, 1082, 1075, 1074, 1087, 1072,
       1069, 1070, 1040, 1091, 1073, 1089, 1056, 1092, 1057, 1085, 1084,
       1077, 1055, 1088, 1064, 1046, 1103, 1086, 1025, 1071, 1096, 1027,
       1095, 1065, 1022, 1081, 1098, 1048, 1050, 1034, 1023, 1018, 1044,
       1061, 1052, 1009, 1053, 1058, 1093, 1102, 1066, 1051, 1042, 1062,
       1026, 1035, 1029, 2004, 1031, 1049, 1036, 1101, 1037, 1014, 1033,
       1041, 4012, 1047, 1039, 1013, 1099, 1019, 1021, 1043, 1020, 1032,
       2002, 1015, 1030, 1100, 1024, 1104, 1017, 2001, 1002, 1016, 1012,
       1008, 1006, 2003, 1003, 1107, 1007, 5001, 5002, 1005, 4017, 5003,
       5018, 6022, 1106, 2011, 4007, 1110, 1001, 4015, 2009, 2008, 1105,
       1004, 4003, 1010, 2006, 5009, 4009, 6010, 4023, 5011, 4001, 6034,
       1011, 4013, 4010, 6055, 4025, 4008, 4005, 6003, 5023, 4006, 5022,
       4002, 6032, 6001, 2007, 2005, 6011, 4021, 40

In [24]:
tn_mort_2018['place_of_death'].unique()

array([4, 1, 5, 2, 6, 7, 3])

In [25]:
tn_mort_2018['marital_status'].unique()

array(['M', 'W', 'S', 'D', 'U'], dtype=object)

In [26]:
tn_mort_2018['manner_of_death'].unique()

array([7., 2., 1., 3., 4., 5.])

In [ ]:
tn_mort_2018['manner_of_death'].unique()

In [ ]:
tn_mort_2018['manner_of_death'].unique()

In [ ]:
tn_mort_2018['manner_of_death'].unique()

In [ ]:
tn_mort_2018['manner_of_death'].unique()